baseurl = "https://uxpa.ischool.utexas.edu"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "UXPA UT Austin"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "University of Texas at Austin student chapter of the User Experience Professionals Association"
  logo = "img/longhorn.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Brent Biglin"
  email = "uxpautaustin@gmail.com"
  facebook = "UXPAUTAustin"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  #github = "brentbiglin"
  twitter = "UXPA_UT_Austin"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  instagram = "UXPA_UT_Austin"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Events"
    url = "page/events/"
    weight = 2

[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "UXPA"
    url = "page/uxpa/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Board Members"
    url = "page/board-members/"
    weight = 2

[[menu.main]]
    name = "Become a Member"
    url = "page/become-a-member/"
    weight = 4
